### ISSUE TITLE
investigate slow loading of tiles when using OpenStreetMap

### ISSUE THREAD

**Issue by sothawo** [sothawo/mapjfx#29]
when using OSM tiles are loading really slow. investigate to find the reason why.

**Comment by skinkie** [comment]
Thanks, this bugged me too. +1

**Comment by sothawo** [comment]
in the thread dump I see (not using caching just the plain connections):

```
"URL-Loader-20" #52 daemon prio=5 os_prio=31 tid=0x00007ffc15196800 nid=0x13503 runnable [0x0000700008e32000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        - locked <0x000000076b788690> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x000000076b788700> (a sun.security.ssl.AppInputStream)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x000000076bd350e0> (a java.io.BufferedInputStream)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        - locked <0x000000076b786f10> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        - locked <0x000000076b786f10> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:429)
        at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:165)
        at com.sun.webkit.network.URLLoader.lambda$run$98(URLLoader.java:129)
        at com.sun.webkit.network.URLLoader$$Lambda$279/151954649.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.webkit.network.URLLoader.run(URLLoader.java:128)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x000000076b309c18> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

this means that the native method hangs on read0 while trying to read the https header. Googling shows that this happens sometimes when the http client library does not set timeouts correctly.

Alas this still happens with version 1.8.0_152, although a couple of webview bugs were fixed. And this seems only to happen when connecting to OpenStrretmap.

Will investigate further.

**Comment by sothawo** [comment]
further notice: there seems to be a thread pool of up to 15 Threads (called URL-Loader-NN). When theses threads get stuck in the mentioned `java.net.SocketInputStream.socketRead0` no further URLs are loaded.

These threads will at some time return, but that may be ten or more minutes. The longest Thread runtime I monitored was 15 minutes.

I have no control over these when _not_ using the offline cache. I will try if I can set the timeouts on the connections when managing them in caching mode...

**Comment by skinkie** [comment]
Why don't you use the HTTP version instead of the HTTPS version?

**Comment by sothawo** [comment]
this is beyond my control, these urls are coded in the OpenLayers library. And it's not only related to ssl, because both Bing map types (road and aerial) work with https urls for the tiles without these problems

**Comment by sothawo** [comment]
I have the impression that when running with Java 10 this is not happening anymore. Would be great if other people could check this.

**Comment by s3erjaeh** [comment]
With the XYZ source I provided, you can compare it by using the following xyz url of Open Street Map: https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by ullenboom** [comment]
> I have the impression that when running with Java 10 this is not happening anymore. Would be great if other people could check this.

Happens with OpenJDK-11 also. Super slow.

**Comment by sothawo** [comment]
I still see that too, with OpenJDK 11.0.1 on both macOS an Win10.

**Comment by vewert** [comment]
Using the latest release (1.21.0), and Java 8 and Win10; I switched to try using the new XYZ source (thanks @s3erjaeh). Using: https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png was still very slow, but I tried some others: https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.png and https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png and they seem much faster.
Could it just be, that the tile.openstreetmap.org servers are just serving the tiles really slowly, and its not an issue with the library? Just a thought.

**Comment by sothawo** [comment]
That's right, only OSM and Stamen (which is based on OSM) is affected by this. This started when OSM switched to https, but I do not have the problems using OSM in a browser, it seems to be some strange behaviour in the SSL traffic handling, see the thread dump I posted earlier.

**Comment by skinkie** [comment]
I wonder if this could be something in Java itself that can't handle SSL False Start. Virtually every https server implements this at this moment.

**Comment by sothawo** [comment]
strange thing is that Bing Maps uses https as well; and it's not permanenty reproducible.
