### ISSUE TITLE
loading of javascript and css does not work when running on Windows

### ISSUE THREAD

**Issue by sothawo** [sothawo/mapjfx#4]
the changes made to fix the broken behaviour in JDK8u60 do not work on Windows:

2015-10-18 14:07:38:121 MESZ FEINER com.sothawo.mapjfx.MapView initialize:  initializing...
2015-10-18 14:07:38:122 MESZ FEINER com.sothawo.mapjfx.MapView loadMapViewHtml:  loading from file:/C:/Users/peter/Entwicklung/mapjfx/target/classes/mapview.html
2015-10-18 14:07:38:128 MESZ FEINER com.sothawo.mapjfx.MapView processHtmlLine:  loading from ol/3.9.0/ol.css
2015-10-18 14:07:38:128 MESZ SCHWERWIEGEND com.sothawo.mapjfx.MapView processHtmlLine:  loading ol/3.9.0/ol.css
java.net.MalformedURLException: no protocol: ol/3.9.0/ol.css
        at java.net.URL.<init>(URL.java:586)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at com.sothawo.mapjfx.MapView.processHtmlLine(MapView.java:702)
        at com.sothawo.mapjfx.MapView.lambda$loadMapViewHtml$37(MapView.java:664)
        at com.sothawo.mapjfx.MapView$$Lambda$89/1818968241.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.sothawo.mapjfx.MapView.loadMapViewHtml(MapView.java:666)
        at com.sothawo.mapjfx.MapView.initialize(MapView.java:510)
        at com.sothawo.mapjfx.TestApp.start(TestApp.java:134)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
        at com.sun.javafx.application.LauncherImpl$$Lambda$54/2018266402.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl$$Lambda$50/2121839127.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl$$Lambda$52/1521682452.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
        at com.sun.javafx.application.PlatformImpl$$Lambda$51/1165560644.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
        at com.sun.glass.ui.win.WinApplication$$Lambda$40/78749362.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sothawo** [comment]
fixed
