### ISSUE TITLE
Problem with more than a few MapViews

### ISSUE THREAD

**Issue by joha78** [sothawo/mapjfx#45]
Hi sothawo,

I was on my way switching from GMapsFx (https://github.com/rterp/GMapsFX) to mapjfx.
But unfortunately I am having the problem that I can't open more than 20 MapViews safely. 

It's not that I am viewing all of them in one pane, its about creating a MapView, using it, throwing it away and creating a new one. I am not sure what's going on, but probably its some kind of memory leak. 

I am using JDK/JRE jdk1.8.0_192 on Mac OS X. Any ideas or suggestions?

Thank you very much.
Jörg

When the MapView stops working I am getting this exception:

java.lang.NullPointerException
	at com.sun.javafx.webkit.prism.RTImage.getTexture(RTImage.java:81)
	at com.sun.javafx.webkit.prism.RTImage.getGraphics(RTImage.java:69)
	at com.sun.javafx.webkit.prism.WCBufferedContext.getGraphics(WCBufferedContext.java:64)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext$Composite.paint(WCGraphicsPrismContext.java:1497)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawImage(WCGraphicsPrismContext.java:842)
	at com.sun.webkit.graphics.GraphicsDecoder.drawImage(GraphicsDecoder.java:427)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:184)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:92)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:103)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:110)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:340)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:92)
	at com.sun.webkit.WebPage.paint2GC(WebPage.java:734)
	at com.sun.webkit.WebPage.paint(WebPage.java:701)
	at com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:96)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:323)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sothawo** [comment]
strange stacktrace. I never did create and discard a MapView in a program so often; I'll to to reproduce this.

**Comment by joha78** [comment]
I created a demo for this problem. Just press the "Add one map" button until the new map does not load its data anymore. This happens if I close each old map before and when just adding new ones.  I have the feeling that it is something about the complexity of the map, but I have not verified until now.  

https://github.com/joha78/mapjfx-problem-demo

**Comment by joha78** [comment]
I am running the app out of IntelliJ. I try it on command line later. That sounds strange.

**Comment by sothawo** [comment]
I started your test app with
```
-Dprism.debug=true -Dprism.pooldebug=true -Dprism.poolstats=true -Dprism.verbose=true
```
and that showed that this probably is a prolem with es vram pool:

```
ES2 Vram Pool: 536.708.096 used (100,0%), 536.870.912 target (100,0%), 536.870.912 max
```

This is pretty lowlevel Javafx stuff, where I am not sure how this could be handled. I found this page: https://wiki.openjdk.java.net/pages/viewpage.action?pageId=20415996 but I do not know at the moment how this could be handled from MapView's side. I'll keep on searching later.

**Comment by joha78** [comment]
I tried changing my example in a way that it creates Tabs with Labels inside. If I close all Tabs all the Labels are discarded by GC. If I replace the Labels with MapViews and close all Tabs, the Tabs and MapViews are not discarded anymore. Maybe it is the MapView-WeakRef-Cleaner?

**Comment by joha78** [comment]
I can easily create >=30 tabs with MapViews if I resize the window like 100x100 px. If I maximize the window it is possible to open about 5 tabs.

**Comment by joha78** [comment]
I found a "workaround". It's running the app with -Dprism.order=sw
Obviously, it does not solve the problem with not garbage collecting the MapView.

**Comment by sothawo** [comment]
yes, I think the MapView should be gc'ed, but the the `DetachableTab`s holding a reference to the `MapView`s aren't collected either. Does closing a tab by clicking the 'x' release the objjects created in this tab?

**Comment by sothawo** [comment]
I have added a method `MapView.close()` which will stop the background thread that cleans the weak references. This is in 1.20.0 for JDK 8 and 2.1.0 for JDK 11, should be available in maven central tomorrow. I changed the code in your sample to:
```
        addButton.setOnAction(event -> {
            if (bingMapsApiKeyField.getText() == null || bingMapsApiKeyField.getText().trim().isEmpty()) {
                DetachableTab newTab = new DetachableTab("Error", new Label("Please provide an API key for bing maps"));
                tabPane.getTabs().add(newTab);
                tabPane.getSelectionModel().select(newTab);
            } else {
                DetachableTab newTab =
                        new DetachableTab("Map") {
                            {
                                final MapView mapView = buildMap();
                                setContent(mapView);
                                setOnClosed(evt -> {
                                    System.out.println("tab closed");
                                    mapView.close();
                                    setContent(null);
                                });
                            }

                        };
                tabPane.getTabs().add(newTab);
                tabPane.getSelectionModel().select(newTab);
            }
        });
```
to call this method when the tab is closed (and releasing the MapView object by setting the tab's content to null). With this, when opening and closing multiple tabs, and after triggering a garbage collection, the MapView instances are gone.

I could open tabs and close them without getting the error (stooped after 40 tabs) without explicitly triggering a gc.

Please try if this works for you as well.

**Comment by joha78** [comment]
Yes. That works. Thank you. In my real app its a bit more complicated. I need to figure out a way how to call close() from the Tab, because my Tab does not (and should not) know about it's content. But that should be possible.

Nevertheless, its not possible to open more than 6 fullscreen maps at the same time :-(
